version: '3'
services:
  web:
    image: "docker-node-mongo-todo-app"
    build: .
    command: "node server.js"
    ports:
      - "4000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27001:27017"
